CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) NOT NULL,
  "password" text NOT NULL
);

CREATE TABLE "historical_queries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location" varchar(200) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "people" integer NOT NULL,
  "limit" integer NOT NULL,
  "timestamp" timestamp NOT NULL,
  "user_id" integer
);

CREATE TABLE "historical_results" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "description" text NOT NULL,
  "rating" decimal(10,2) NOT NULL,
  "reviews_num" integer NOT NULL,
  "night_cost" integer NOT NULL,
  "total_cost" integer NOT NULL,
  "query_id" integer
);

CREATE TABLE "screenshots" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image" bytea NOT NULL,
  "result_id" integer
);

ALTER TABLE "historical_queries" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "historical_results" ADD FOREIGN KEY ("query_id") REFERENCES "historical_queries" ("id");

ALTER TABLE "screenshots" ADD FOREIGN KEY ("result_id") REFERENCES "historical_results" ("id");
