"""empty message

Revision ID: 56736d4a22d6
Revises: a5a73059a09f
Create Date: 2024-09-25 23:52:05.854055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56736d4a22d6'
down_revision = 'a5a73059a09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('expiration')

    # ### end Alembic commands ###
